# voiceguard/render.yaml

services:
  # A Redis instance for our Django Channels layer
  - name: redis
    type: pserv # Private Service
    image: redis:alpine # This line is now corrected
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

  # The Django/Daphne Web Service
  - name: web
    type: web
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: pserv
          name: redis
          property: port
      
      - key: DEBUG
        value: False
      
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PERSPECTIVE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false